# Generated by Django 3.1.4 on 2021-11-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_registration',
            fields=[
                ('plate_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('car_owner', models.CharField(max_length=200)),
                ('Owner_Id', models.IntegerField()),
                ('phonenumber', models.CharField(default=0, max_length=50)),
                ('car_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('Time_done', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Car_registration',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car_registration', models.ManyToManyField(to='Bic.Car_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_plate', models.CharField(max_length=50, null=True)),
                ('insurance_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car_registration', models.ManyToManyField(to='Bic.Car_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
                ('car_registration', models.ManyToManyField(related_query_name='car_re', to='Bic.Car_registration')),
            ],
        ),
    ]
