# Generated by Django 3.2.5 on 2021-11-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name_plural': 'Control'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name_plural': 'Insurance'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Tax'},
        ),
        migrations.AlterField(
            model_name='control',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
